services:
  - type: web
    name: robo-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn robo_dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0